services:
  - type: web
    name: mcq-generator
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_md
    startCommand: gunicorn app:app
